### ISSUE TITLE
Error reading parameter file

### ISSUE THREAD

**Issue by Athanaseus** [Fil8/RFInder#28]
```
2019-03-14 11:57:17,463 INFO - ------ Reading your parameter file ------
2019-03-14 11:57:17,464 INFO -
2019-03-14 11:57:17,464 INFO - Traceback (most recent call last):
2019-03-14 11:57:17,464 INFO -   File "/usr/local/bin/rfinder", line 31, in <module>
2019-03-14 11:57:17,464 INFO -     rfi_par = RFInder.main([a for a in sys.argv[1:]])
2019-03-14 11:57:17,464 INFO -   File "/usr/local/lib/python2.7/dist-packages/rfinder/__init__.py", line 611, in main
2019-03-14 11:57:17,464 INFO -     self.set_cfg_par()
2019-03-14 11:57:17,464 INFO -   File "/usr/local/lib/python2.7/dist-packages/rfinder/__init__.py", line 288, in set_cfg_par
11:57:17,465 INFO -     msfile = workdir + self.cfg_par[key].get('msname', None)
11:57:17,465 INFO - TypeError: cannot concatenate 'str' and 'list' objects
```

**Comment by Fil8** [comment]
in the new `rfinder_default.yml` msname must be parsed as a simple string and not a list.

**Comment by Athanaseus** [comment]
Thanks. It works.
i.e. `msname` is a file name instead of a list of file names.
